import = [
 "~/dev/sesh.toml"
]

[[session]]
name = "home ğŸ "
path = "~"

[[session]]
name = "code ğŸ’»"
path = "~/dev"

[[session]]
name = "dotfiles â„ï¸"
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "downloads ğŸ“‚"
path = "~/Downloads"
startup_command = "yazi"

