import = [
 "~/dev/sesh.toml",
 "~/dev/github/sesh.toml"
]

[[session]]
name = "home ğŸ "
path = "~"

[[session]]
name = "code ğŸ’»"
path = "~/dev"

[[session]]
name = "dotfiles â„ï¸"
path = "~/.dotfiles"
startup_command = "nvim"

[[session]]
name = "todo dotfiles âœ…"
path = "~/.dotfiles"
startup_command = "nvim docs/todo.md"

[[session]]
name = "kixvim ğŸ‘¨â€ğŸ’»"
path = "~/dev/github/kixvim/"
startup_command = "nvim --cmd ':Telecope find_files'"

[[session]]
name = "downloads ğŸ“‚"
path = "~/Downloads"
startup_command = "yazi"
