---
name: Run renovate

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "30 00 * * 0"

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
      - name: Renovate
        uses: renovatebot/github-action@v46.0.2
        with:
          configurationFile: .github/renovate.json5
          renovate-version: full
          token: ${{ secrets.RENOVATE_TOKEN }}
